name: trips-validation-platform
services:
  trip-simulator:
    extends:
      file: ./trip_simulator/docker/compose.yml
      service: trip-simulator
    networks:
      - trip-validation-platform
      - trip-simulator
    depends_on:
      - trip-ingestion-service

  trip-ingestion-service:
    extends:
      file: ./trip_ingestion_service/docker/compose.yml
      service: trip-ingestion-service
    networks:
      - trip-validation-platform
      - trip-ingestion-service
    depends_on:
      trip-queue:
        condition: service_started
      trip-database:
        condition: service_healthy

  trip-queue:
    extends:
      file: ./trip_ingestion_service/docker/compose.yml
      service: trip-queue
    networks:
      - trip-validation-platform
      - trip-ingestion-service

  trip-database:
    extends:
      file: ./trip_ingestion_service/docker/compose.yml
      service: trip-database
    networks:
      - trip-validation-platform
      - trip-ingestion-service
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  test-trip-database:
    extends:
      file: ./trip_review_service/docker/compose.yml
      service: test-trip-database
    networks:
      - trip-validation-platform
      - trip-review-service

  trip-review-service:
    extends:
      file: ./trip_review_service/docker/compose.yml
      service: trip-review-service
    networks:
      - trip-validation-platform
      - trip-review-service
    depends_on:
      trip-database:
        condition: service_healthy

networks:
  trip-validation-platform:
  trip-simulator:
  trip-ingestion-service:
  trip-review-service: