name: 'Trips Simulator'
services:
  trip-simulator:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - APP_ENV=development
    volumes:
      - ../:/app
    working_dir: /app
    container_name: trip-simulator
