[supervisord]
nodaemon=true

[program:ingestor]
command=python /app/ingestor.py
autostart=true
autorestart=true

[program:pruner]
command=python /app/pruner.py
autostart=true
autorestart=true

[program:uvicorn]
command=uvicorn main:app --host 0.0.0.0 --port 80 --reload-dir /app
autostart=true
autorestart=true

